name: Github Actions Demo
on: push
jobs:
  Example-Actions-Job:
    name: Exploring github actions
    runs-on: ubuntu-latest
    steps:
       # Display the event that triggred the workflow
       - run: echo "The job was triggered by a ${{ github.event_name }} event."
       
       #Runner information
       - run: echo "This job is running on ${{ runner.os }}"
       
       #Info about the repo and branch
       - run: echo "The name of the branch is ${{ github.branch }} and the repo is ${{ github.repository }}"
       
       #Use Action located in https://github.com/actions
       - name: Check out repos code
         uses: actions/checkout@v2
       
       - run: echo "The repo has been copied to the path ${{ github.workspace }} on the runner"
       
       - name: conditional step when event name is pull request
         if: ${{ github.event_name == 'pull_request' }}
         run: echo "This event is a pull request"
         
       - name: List files in the repos
         run: |
            ls ${{ github.workspace }}
       
       - name: Steup dotnet on runner
         uses: actions/setup-dotnet@v1
         with: 
           dotnet-version: '3.x'
          
       - name: Display dotnet version
         run: dotnet --version
       
       - run: echo "This job's status is ${{ job.status }}"
